name: AddToProjectBoard

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/users/takeshun256/projects/2
          # A GitHub personal access token with write access to the project
          github-token: ${{ secrets.GIT_TOKEN }}
          # A comma-separated list of labels to use as a filter for issue to be added
          # labeled: # optional
          # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
          # label-operator: # optional